### ISSUE TITLE
inquiry about Geometry question

### ISSUE THREAD

**Issue by SHITIANYU-hue** [OpenBMB/OlympiadBench#2]
i am wondering about geometry question, how did you put the image into GPT4v, if it is possible to open image from the link?
thanks and look forward your reply 
   {
        "id": 7200,
        "subfield": "Plane Geometry",
        "question": "$如图，已知三角形ABC的顶点为A(2，4)，B(0，-2)，C(-2，3)，求：$![Image](https://cdntk.53zaixian.com/tq/1658661332313509889/img/compression/M_4f1e91419a0becac9533917a5e0f6cc3.jpg)\n$AB边上的高所在直线的方程；$",
        "solution": [
            "$设AB边上的高所在直线的方程为y=-\\frac{1}{3}x+m，由该直线过点C(-2，3)，得3=\\frac{2}{3}+m，解得m=\\frac{7}{3}，故AB边上的高所在直线的方程为y=-\\frac{1}{3}x+\\frac{7}{3}，即x+3y-7=0.$"
        ],
        "final_answer": [
            "$x+3y-7=0$"
        ],
        "is_multiple_answer": false,
        "unit": null,
        "answer_type": "Equation",
        "error": null,
        "label": "Open-ended_Questions",
        "source": "Gaokao_Maths_mock_exam",
        "support_auto_scoring": true,
        "classification": "Gaokao_Mathematics"
    },

**Comment by Hothan01** [comment]
We follow the GPT-4V case for inputting images. We have posted the [code](https://github.com/OpenBMB/OlympiadBench/tree/main/inference) and hope it helps you.
Also, we have made an update to the dataset. In the new version of the dataset, the images are already downloaded, not in the form of links.
