### ISSUE TITLE
Possible mislabelled subfield 

### ISSUE THREAD

**Issue by JvThunder** [OpenBMB/OlympiadBench#3]
Hello, our research team would be happy to integrate Olympiad Bench evaluation dataset to our [evaluation suite](https://github.com/EvolvingLMMs-Lab/lmms-eval).

However, we noticed that there might be possible mislabeling of subfield for id 1797 as shown in the image below:
![image](https://github.com/OpenBMB/OlympiadBench/assets/44111143/3b29cc9b-57ec-484b-b49c-c6fa1d8eb7c3)
We believe that this is meant to be a `Geometry` subfield instead of `Number Theory`.

If so, we can correct this example when integrating it to our pipeline. We can also inform possible errors in the future.

**Comment by Hothan01** [comment]
I appreciate your interest in OlympiadBench. You're right about the subfield here, and we've corrected it. In addition, the format of data has been updated, you can use the latest version.
We welcome your valuable suggestions to our work.
