### ISSUE TITLE
Several typos in figure 1 of the paper.

### ISSUE THREAD

**Issue by weiyx16** [OpenBMB/OlympiadBench#5]
I'd like to point out several typos in the illustration of OlympiadBench dataset, i.e. figure 1 in the paper.
+ The correct question is $... =2012(xyz+2)$ instead of $... =2012(xyz+z)$
+ Middle step: *...So $x=1$ or $y=1$* is wrong, which should be *...So $x=1$ or $x=2$*

Luckily, it's correct in the raw dataset. But I can't find a Chinese version of this question in the raw dataset with id=2165, but only find the English version. It will be great to know where it is.

**Comment by Hothan01** [comment]
Thanks for the correction, it's very helpful.

BTW, this question is from IMO, the original question is in English and there is no Chinese version.

If you have other questions, we can continue to exchange and learn.

**Comment by weiyx16** [comment]
Thank you for your kind response. Nice work~
